# Generated by Django 3.1.4 on 2021-04-01 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_order',
            name='podcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account_podcategory'),
        ),
        migrations.AlterField(
            model_name='account_podcategory',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.account_category'),
        ),
    ]
