# Generated by Django 3.1.4 on 2021-06-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_task_meet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_meet',
            name='notification',
            field=models.DateTimeField(null=True),
        ),
    ]
