# Generated by Django 3.2.7 on 2021-09-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_task_meet_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_meet',
            name='date_do',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task_meet',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task_meet',
            name='client_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='task_meet',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
