# Generated by Django 3.2.7 on 2021-09-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0004_auto_20210907_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_meet',
            name='notification',
            field=models.BooleanField(null=True),
        ),
    ]
