# Generated by Django 3.2.7 on 2021-09-07 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210401_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Цвета',
                'verbose_name_plural': 'Цвет',
            },
        ),
        migrations.CreateModel(
            name='Remainder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('summa', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.account_category')),
            ],
            options={
                'verbose_name': 'Остатки',
                'verbose_name_plural': 'Остаток',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.IntegerField()),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.account_category')),
            ],
            options={
                'verbose_name': 'Бюджеты',
                'verbose_name_plural': 'Бюджет',
            },
        ),
        migrations.AddField(
            model_name='account_order',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.color_order'),
        ),
    ]
