# Generated by Django 3.1.4 on 2021-03-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_meet',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
